// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeftgkjgowudepewtbxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlZnRna2pnb3d1ZGVwZXd0YnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTYyNzYsImV4cCI6MjA2Nzg3MjI3Nn0.Hw_8jLzUAEpH3L6I60X2alI01Ybis05h_l5q42lchEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});